### ISSUE TITLE
[Enhancement] => Improvements to Fuzzing Modules

### ISSUE THREAD

**Issue by edgylivingstone** [theInfectedDrake/TIDoS-Framework#10]
Hi there,
This is really a great work. However there are really some good scopes for improvement of the fuzzing modules. For example, you can make the scripts to ask for the wordlist first before the fuzzing begins. Also, support for multiple parameters need to be added, since this version only takes in a single parameter.

And for the `API_KEYS`, you can just write up a Python file as `API_KEYS.py` and import the keys for the respective modules like `SHODAN`, `CENSYS`, `FULL CONTACT` and `WHATCMS`, instead of the `config.json` file.

Thanks,

**Comment by theInfectedDrake** [comment]
Sure! I will look to it. Thank you! I am assigning this in v1.4 of my project.

**Comment by henrydogard** [comment]
Everything is done as promised, great work @theInfectedDrake ... 😮👌

**Comment by theInfectedDrake** [comment]
The `API_KEYS` have been looked after. Now its time to take a look at support for multiple parameters.
