### ISSUE TITLE
Problem to run TIDoS - clean installation

### ISSUE THREAD

**Issue by ThOhT** [theInfectedDrake/TIDoS-Framework#15]
Hi, I just installed TIDoS using sudo. It's seems to be installed fine, but when I try to run it, I got this error:

```
 File "/opt/tidos-framework/tidos.py", line 18
    print R+' [-] User Interruption Detected!'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(R+' [-] User Interruption Detected!')?
```
My default python version is 3.6.6.
How can I solve this problem?

**Comment by theInfectedDrake** [comment]
TIDoS is coded purely on Python 2.x. Run the program in a Python2 environment.

**Comment by ThOhT** [comment]
I changed my default python version to 2.7.15, but it shows the same error:

> $sudo tidos
>  File "/opt/tidos-framework/tidos.py", line 18
>     print R+' [-] User Interruption Detected!'
>           ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(R+' [-] User Interruption Detected!')?
> 
> 

And my python version
```
$ python --version
Python 2.7.15
```
