### ISSUE TITLE
Give credits to WAScan

### ISSUE THREAD

**Issue by s0md3v** [theInfectedDrake/TIDoS-Framework#19]
Hi there,

Looks like the WAF signatures are copied from [WAScan](https://github.com/m4ll0k/WAScan).

[TIDoS Signatures](https://github.com/theInfectedDrake/TIDoS-Framework/tree/master/files/signature-db/waf-signatures) | [WAScan Signatures](https://github.com/m4ll0k/WAScan/tree/master/plugins/fingerprint/waf)

WAScan's license however permits people to modify and redistribute the code but this isn't a really nice thing to do. You should give credits.

Thanks.

**Comment by theInfectedDrake** [comment]
Well, I guess you should have opened the files at least and gone through the contents... :')

Credits already given. 😛

**Comment by s0md3v** [comment]
This isn't how you give credits. Original author worked hard to curate all those signatures and it should be mentioned int he readme.

And what did you "modify" anyway? Variable names?

### WAScan
```python
def airlock(headers,content):
	_ = False
	for header in headers.items():
		_ |= search(r'\AAL[_-]?(SESS|LB)=',header[1],I) is not None
		if _ : break 
	if _:
		return "Airlock (Phion/Ergon)" 
```

### TIDoS
```python
def airlock(headers,content):
	detect = False
	for header in headers.items():
		detect |= search(r'\AAL[_-]?(SESS|LB)=',header[1],I) is not None
		if detect : 
			break
	if detect:
		return "Airlock (Phion/Ergon)" 
```

**Comment by theInfectedDrake** [comment]
Well, well, well, "Mr. Code Guardian" have a look at Ekultek's [WhatWaf signatures](https://github.com/Ekultek/WhatWaf/tree/master/content/plugins) and WafW00f [WAF Signatures](https://github.com/Ekultek/WhatWaf/tree/master/content/plugins). And as far as I guess, Wafw00f is the oldest application in WAF detection. Now go and raise an issue on WAScan 😛 as well as Whatwaf. And until you make sure that everyone has given appropriate credits, mate lets stop talking about this.

At least, I gave credits wherever reqd. and [accepted](https://github.com/theInfectedDrake/TIDoS-Framework/issues/20) wherever I missed out, at least I did not do something like what you did [here](https://github.com/s0md3v/Breacher/issues/2).
