### ISSUE TITLE
Give credits to XSSTracer

### ISSUE THREAD

**Issue by s0md3v** [theInfectedDrake/TIDoS-Framework#20]
The [xsstracer](https://github.com/theInfectedDrake/TIDoS-Framework/blob/master/modules/0x03-VulnLysis/0x01-MiscBugs/xsstrace.py) module is a copy paste from Crowdshield's [XSSTracer](https://github.com/1N3/XSSTracer/blob/master/xsstracer.py).

XSSTracer doesn't have a license. According to international standards, that means no one has the right to use it's code.
Either remove it or at least give credits.

**Comment by theInfectedDrake** [comment]
I have to admit, I missed credits. 

However its not a total copy paste :'). A part of it is modded to suit the purpose. 🙂

**Comment by theInfectedDrake** [comment]
Done!
