### ISSUE TITLE
No module named sslyze

### ISSUE THREAD

**Issue by Ondrik8** [theInfectedDrake/TIDoS-Framework#27]
#pip install sslyze
Collecting sslyze
Requirement already satisfied: typing; python_version < "3.5" in /usr/lib/python2.7/dist-packages (from sslyze) (3.6.4)
Requirement already satisfied: cryptography==2.2.2 in /usr/local/lib/python2.7/dist-packages (from sslyze) (2.2.2)
Collecting nassl<1.2.0,>=1.1.0 (from sslyze)
  Using cached https://files.pythonhosted.org/packages/98/53/2c32ddd229eb80e542b24ac5ac8a8f3bb31532069ae2554ebff6368e83ee/nassl-1.1.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting tls-parser<1.3.0,>=1.2.0 (from sslyze)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from sslyze) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.11.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.11.5)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (2.7)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.0.22)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography==2.2.2->sslyze) (2.18)
Installing collected packages: nassl, tls-parser, sslyze
  Found existing installation: nassl 0.12
Cannot uninstall 'nassl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>
    import sslyze
ImportError: No module named sslyze

**Comment by theInfectedDrake** [comment]
This is your distro dependency error, not a fault of TIDoS.

At best, I can suggest doing an uninstall via `pip uninstall sslyze` and then doing a `pip install --upgrade --force-reinstall sslyze` to force reinstall, and if still that doesn't solve your problem, try doing `pip install --ignore-installed sslyze`, to ignore the already installed package (reinstalling instead).

Also note that your default `pip` must be `pip2`, or better try doing via `pip2 install ...`.
