### ISSUE TITLE
ImportError: No module named sslyze

### ISSUE THREAD

**Issue by hihackthis** [theInfectedDrake/TIDoS-Framework#28]
Hi

I found TIDoS in Google and I wanted to test it, I installed with success.

But when I run it:

```
# tidos 
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>
    import sslyze
ImportError: No module named sslyze
```

It is updated:

```
# python tidos_updater.py 

   ===============
    U P D A T E R
   ===============

 [*] Looking up for the latest version...
 [!] The version on GitHub is : v1.6.0
 [!] The version you have is : v1.6.0

 [!] You are using the latest version of this framework!
```

And my Kali too:

```
# grep VERSION /etc/os-release
VERSION="2018.3"
VERSION_ID="2018.3"
```
Info:

```
# pip install sslyze
Collecting sslyze
Requirement already satisfied: typing; python_version < "3.5" in /usr/lib/python2.7/dist-packages (from sslyze) (3.6.6)
Requirement already satisfied: cryptography==2.2.2 in /usr/local/lib/python2.7/dist-packages (from sslyze) (2.2.2)
Collecting nassl<1.2.0,>=1.1.0 (from sslyze)
  Using cached https://files.pythonhosted.org/packages/98/53/2c32ddd229eb80e542b24ac5ac8a8f3bb31532069ae2554ebff6368e83ee/nassl-1.1.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting tls-parser<1.3.0,>=1.2.0 (from sslyze)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from sslyze) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.11.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.11.5)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages/idna-2.7-py2.7.egg (from cryptography==2.2.2->sslyze) (2.7)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography==2.2.2->sslyze) (1.0.17)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography==2.2.2->sslyze) (2.18)
Installing collected packages: nassl, tls-parser, sslyze
  Found existing installation: nassl 0.12
Cannot uninstall 'nassl'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Can you help me?

Regards

**Comment by theInfectedDrake** [comment]
Uh ho, another `sslyze` ImportError.

Actually there isn't much I can do here to fix. At best I can suggest some remediation steps. This is same as #27. Try following the steps I mentioned there. So `nassl` being a distutils project, pip cannot properly uninstall packages installed by "pure" distutils, because distutils doesn't record enough metadata for pip to do so. So it runs into a interruption and hence `sslyze` isn't getting installed. As told there, try doing `pip2 install --ignore-installed sslyze`. Lets see whether that solves your problem. 

If this doesn't solve your problem the only option you're left with is to navigate to your `dist-packages/` or `site-packages/` folder and remove the `nassl` installation folder. After that try doing a `pip install sslyze` and everything should be fine. ;)

Since this is an error generated due to your OS, and not an error generated due to some bug in TIDoS, I am closing this for now.

**Comment by suvastar** [comment]
root@kali:~# tidos
Traceback (most recent call last):                            File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>                                              import sslyze
ImportError: No module named sslyze
root@kali:~#

The above problem I got in my nethuter terminal while executing tidos. Any help please.

**Comment by jepunband** [comment]
hi same error here, tried "pip2 install --ignore-installed sslyze" did not work.

root@kali:~/tidos-framework# pip2 install --ignore-installed sslyze
Collecting sslyze
  Using cached https://files.pythonhosted.org/packages/53/67/c8dc163326a4cafc31e2b37a11090d6d98e4811b8820aac87452d82dd205/SSLyze-1.4.3.tar.gz
Collecting nassl<1.2.0,>=1.1.0 (from sslyze)
  Could not find a version that satisfies the requirement nassl<1.2.0,>=1.1.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
No matching distribution found for nassl<1.2.0,>=1.1.0 (from sslyze)

------------------------------------------------------------------------------------------------

# tidos 
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>
    import sslyze
ImportError: No module named sslyze
