### ISSUE TITLE
[Invalid] => ImportError: No module named sslyze

### ISSUE THREAD

**Issue by glenncoco44** [theInfectedDrake/TIDoS-Framework#32]
The install of tidos completes successfully but when i try to run the application i get the following error:

ImportError: No module named sslyze

i have confirmed sslyze is installed on my machine - sslyze is already the newest version (0.12-0kali1)

I am attempting to run the app on Parrot OS updated to the newest version

**Comment by theInfectedDrake** [comment]
Are you running this on Python 2? Is Python 2 your default py version? I just made a commit 177bbf7, which might fix your problem. Also try having a look at #28, a similar problem to yours.
