### ISSUE TITLE
[Suggestion] => Suggestion for dependencies

### ISSUE THREAD

**Issue by ugurcemozturk** [theInfectedDrake/TIDoS-Framework#38]
Hey again.
When I look for  the issues of your nice project, I see that there are lots of people have faced with the dependency problem.

As you mentioned earlier, it's **not about the functionality of the TIDoS** but it may help people to **_use and contribute_** to the project.

Maybe you can add a _requirements.txt_ or improve the _./install_ script.
From now,  I faced with almost 10 dependency issue.

I would like to help to you about it, no worries ;)
Thx
ugurcem

**Comment by theInfectedDrake** [comment]
This was just what I was thinking. A `requirements.txt`file would solve the Python dependencies but there are still some deoendency which need to be installed via `aptitude` or `yum`. I am thinking of including some instructions on README for a manual installation.

**Comment by ugurcemozturk** [comment]
Perfect!

We can solve it other dependencies with Dockerize it, but still, Docker will stay as a dependency.
So what I suggest is let's wait for requirements.txt to proceed.

Thx;)
ugurcem

**Comment by theInfectedDrake** [comment]
I added a [small change to the README file](https://github.com/theInfectedDrake/TIDoS-Framework/blob/master/README.md#manual-installation-locally-) about the manual installation and have added the `[requirements.txt](https://github.com/theInfectedDrake/TIDoS-Framework/blob/master/requirements.txt)` file as said.

**Comment by ugurcemozturk** [comment]
You rock.
