### ISSUE TITLE
Error at Installing `install`

### ISSUE THREAD

**Issue by Loner-Coder** [theInfectedDrake/TIDoS-Framework#5]
Hi there,

I recently found your repo and decided to test it out. But unfortunately, I faced with some exceptions while running the install file. I did a `./install` but the result is:

```
Traceback (most recent call last):
    File "modules/PassiveRecon/googledorker.py", line 26, in <module>
        import google
ImportError: No module named google
```
Any idea how to fix this?

**Comment by theinfecteddrake** [comment]
Hmm, seems like there is some serious trouble with the code at `googledorker.py`. Let me push some changes that might prevent this error.

**Comment by theInfectedDrake** [comment]
Hi there, I pushed some changes. Try a fresh clone and tell me what is the status. 🙂

**Comment by Loner-Coder** [comment]
Hmm, seems the bug was resolved. Gotcha!

**Comment by theInfectedDrake** [comment]
Yo!
