### ISSUE TITLE
[Invalid] - TIDoS on Win7 Python2

### ISSUE THREAD

**Issue by pedrodj** [theInfectedDrake/TIDoS-Framework#7]
Hi mate, 
thank you for your work!

***
 [!] Gathering info...
 [*] Checking your resources...
Traceback (most recent call last):
  File "./install", line 19, in <module>
    install()
  File "setup/install.py", line 28, in install
    if os.geteuid() == 0:
AttributeError: 'module' object has no attribute 'geteuid'
***

Any help ? :)

**Comment by theInfectedDrake** [comment]
I am really sorry to say that TIDoS is built for running on `Linux` based distros. :(

The dependencies are totally suited for Linux based systems only. Though, I hope of adding Windows Support too in future.

**Comment by pedrodj** [comment]
Thank you for the answer :)
