### ISSUE TITLE
[Feature Request] => IP Configuration at sshbrute.py

### ISSUE THREAD

**Issue by Jeremy0xsebastian** [theInfectedDrake/TIDoS-Framework#8]
Hi there, 

Thank you for this wonderful work. However, I ran into a big error while running the`sshbrute` module. The target gets locked automatically with the IP address of the host website. Can you please modify the code to ask for the IP address host first before the bruteforce starts.

Thank you.

**Comment by theInfectedDrake** [comment]
Okay! I will look to it. Thank you for this feature request.

**Comment by theInfectedDrake** [comment]
I did a small change to the code. Can you try a new fresh clone and tell me if everything is good?
